<!--< ?php
include('acciones.php');
?>-->
<div onMouseOver="showdiv(event,'<?php echo MENU_ALT_ADMINISTRAR_INSPECCION; ?>');" onMouseOut="hiddenDiv()" style='display:table;margin-top3px;'><a href="?seccion=inspecciones_admin&aktion=add"><i class="fa fa-plus" style="position:absolute; left:0px; top:0px; color:#ffffff;"></i></a></div>
<div onMouseOver="showdiv(event,'<?php echo MENU_ALT_ADMINISTRAR_INSPECCION; ?>');" onMouseOut="hiddenDiv()" style='display:table;margin-top3px;'><a href="?seccion=inspecciones_admin&aktion=change"><i class="fa fa-edit" style="position:absolute; left:30px; top:0px; color:#ffffff;"></i></a></div>
<div onMouseOver="showdiv(event,'<?php echo MENU_ALT_IMPRIMIR_INSPECCION; ?>');" onMouseOut="hiddenDiv()" style='display:table;margin-top3px;'><a href="?seccion=inspecciones_print&amp;aktion=print"><i class="fa fa-print" style="position:absolute; left:60px; top:0px; color:#ffffff;"></i></a></div>
<div onMouseOver="showdiv(event,'<?php echo MENU_ALT_BORRAR_INSPECCION; ?>');" onMouseOut="hiddenDiv()" style='display:table;margin-top3px;'><a href="?seccion=checkbox3_inspecciones"><i class="fa fa-trash" style="position:absolute; left:90px; top:0px; color:#ffffff;"></i></a></div>
<div onMouseOver="showdiv(event,'<?php echo MENU_ALT_BUSCAR_INSPECCION; ?>');" onMouseOut="hiddenDiv()" style='display:table;margin-top3px;'><a href="?seccion=buscainspecciones"><i class="fa fa-search" style="position:absolute; left:120px; top:0px; color:#ffffff;"></i></a></div>
<div onMouseOver="showdiv(event,'<?php echo LISTA; ?>');" onMouseOut="hiddenDiv()" style='display:table;margin-top3px;'><a href="?seccion=listainspecciones"><i class="fa fa-list-ol" style="position:absolute; left:150px; top:0px; color:#ffffff;"></i></a></div>
<div onMouseOver="showdiv(event,'<?php echo MENU_ALT_JOIN_INSPECCIONES; ?>');" onMouseOut="hiddenDiv()" style='display:table;margin-top3px;'><a href="?seccion=inspecciones_por_servicio&amp;aktion=print"><i class="fa fa-retweet" style="position:absolute; left:180px; top:0px; color:#ffffff;"></i></a></div>
<div onMouseOver="showdiv(event,'<?php echo INSPECCIONES_ANADIR_CODIGOSINCIDENCIA; ?>');" onMouseOut="hiddenDiv()" style='display:table;margin-top3px;'><a href="?seccion=codigosincidenciasinspecciones_admin&aktion=add"><i class="fa fa-plus" style="position:absolute; left:210px; top:0px; color:cornsilk;"></i></a></div>
<div onMouseOver="showdiv(event,'<?php echo INSPECCIONES_MODIFICAR_CODIGOSINCIDENCIA; ?>');" onMouseOut="hiddenDiv()" style='display:table;margin-top3px;'><a href="?seccion=codigosincidenciasinspecciones_admin&aktion=change"><i class="fa fa-pencil" style="position:absolute; left:230px; top:0px; color:cornsilk;"></i></a></div>
<div onMouseOver="showdiv(event,'<?php echo BORRAR; echo "&nbsp;"; echo CODIGO_INCIDENCIA;?>');" onMouseOut="hiddenDiv()" style='display:table;margin-top3px;'><a href="?seccion=checkbox3_codigosincidenciasinspecciones"><i class="fa fa-trash" style="position:absolute; left:260px; top:0px; color:cornsilk;"></i></a></div>
<div onMouseOver="showdiv(event,'<?php echo MEDICIONES; ?>');" onMouseOut="hiddenDiv()" style='display:table;margin-top3px;'><a href="?seccion=tabsframesmediciones"><i class="fa fa-line-chart" style="position:absolute; left:290px; top:0px; color:white;"></i></a></div>
