<?php
/* $Id: lang_DE.inc,v 1.2 2004/07/20 09:30:40 jfenin Exp $ */

define("REFERER",                       "Herkunft");
define("LASTACCESS",                    "letzter Zugriff");
define("ACCESSCOUNT",                   "Anzahl");
define("USERAGENT",                     "Browser");
define("UNKNOWN_REFERER",               "(unbekannt)");
define("UNKNOWN_USERAGENT",             "(unbekannt)");
define("DATE_AND_TIME",                 "%d.%m.%Y %H:%M:%S");
?>