<?php
/* $Id: lang_EN.inc,v 1.2 2004/07/20 09:30:40 jfenin Exp $ */

define("REFERER",                       "Referer");
define("LASTACCESS",                    "last access");
define("ACCESSCOUNT",                   "count");
define("USERAGENT",                     "browser");
define("UNKNOWN_REFERER",               "(unknown)");
define("UNKNOWN_USERAGENT",             "(unknown)");
define("DATE_AND_TIME",                 "%d-%b-%Y %H:%M:%S");
?>