<?php
/**
* Mod gráficas por cliente
* 
* PHP version 5
* 
* @category Mod
* @package  Handy-q
* @author   JJuan <javier@textblock.org>
* @license  http://www.gnu.org/copyleft/gpl.html GNU General Public License
* @link     http://www.textblock.org
*/
?>
<?php 
	require 'includes/config.php'; 
		require '../lang/spanish.lang.php';
		include('../configPDO.php'); 
    require_once ("../includes/mysqli.php");

//if not logged in redirect to login page
if(!$user->is_logged_in()){ header('Location: login.php'); } 
	
	

?>

<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <title>Administración de analíticas de clientes</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="../assets/css/bootstrap.css" rel="stylesheet">
    <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="../assets/css/docs.css" rel="stylesheet">
	<link type="text/css" rel="stylesheet" href="../font-awesome-4.4.0/css/font-awesome.min.css">
	<link type="text/css" rel="stylesheet" href="../assets/css/thickbox.css"  media="screen" />
	    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="../assets/ico/favicon.png">
	
	<style type="text/css"> 
.ToolText{position:relative; } 
.ToolTextHover{position:relative;} 
.ToolText span{display: none;} 

 
.ToolTextHover span {
    zoom: 1;
    filter: alpha(opacity=60);
    opacity: 0.6;
    display: block;
    position: absolute;
    border: 1px solid #006CDC;
    border-radius: 7px;
    top: -2.7em;
    left: 19px;
    background-color: #FFEB3B;
    color: #040404;
    text-align: center;
    padding: 10px;
    font-weight: 700;
}

/** 
* Generated by www.formstylegenerator.com 
**/

/** You can use this style for your INPUT, TEXTAREA, SELECT elements **/
.myinputstyle {
    border: 1px solid #5b047b;
    /** remember to change image path **/
    background: url(none) no-repeat #d2def2;
    font-family: tahoma, helvetica, sans-serif;
    font-style: normal;
    font-size: 14px;
    color: #454743;
}

/** You can use this style for your LABEL elements **/
.mylabelstyle {
    font-family: tahoma, helvetica, sans-serif;
    font-style: bold;
    font-size: 13px;
    color: #82983e;
}

/** 
*  You can use this style for your INPUT, TEXTAREA, SELECT elements 
*  for onmousehover event
**/
.myinputstyle:hover {
    border: 1px solid #FFFFFF;
    /** remember to change image path **/
    background: url(none) no-repeat #FFFFFF;
    color: #454743;
}

</style>


    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
   <link rel="shortcut icon" href="assets/ico/favicon.png">
   
   <script src="../libraries/RGraph.common.core.js" type="text/javascript"></script>
<script src="../libraries/RGraph.line.js" type="text/javascript"></script>
<script src="../libraries/RGraph.common.dynamic.js" type="text/javascript"></script>
<script src="../libraries/RGraph.common.context.js" type="text/javascript"></script>
<script src="../libraries/RGraph.common.tooltips.js" type="text/javascript"></script>
<script src="../libraries/RGraph.common.annotate.js" type="text/javascript"></script>

	<script type="text/javascript"
	src="https://apis.google.com/js/plusone.js"></script>
    <script   
   src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js">
    </script>
    <script>

    function scrolify(tblAsJQueryObject, height){
        var oTbl = tblAsJQueryObject;

        // for very large tables you can remove the four lines below
        // and wrap the table with <div> in the mark-up and assign
        // height and overflow property  
        var oTblDiv = $("<div/>");
        oTblDiv.css('height', height);
        oTblDiv.css('overflow','scroll');               
        oTbl.wrap(oTblDiv);

        // save original width
        oTbl.attr("data-item-original-width", oTbl.width());
        oTbl.find('thead tr td').each(function(){
            $(this).attr("data-item-original-width",$(this).width());
        }); 
        oTbl.find('tbody tr:eq(0) td').each(function(){
            $(this).attr("data-item-original-width",$(this).width());
        });                 


        // clone the original table
        var newTbl = oTbl.clone();

        // remove table header from original table
        oTbl.find('thead tr').remove();                 
        // remove table body from new table
        newTbl.find('tbody tr').remove();   

        oTbl.parent().parent().prepend(newTbl);
        newTbl.wrap("<div/>");

        // replace ORIGINAL COLUMN width                
        newTbl.width(newTbl.attr('data-item-original-width'));
        newTbl.find('thead tr td').each(function(){
            $(this).width($(this).attr("data-item-original-width"));
        });     
        oTbl.width(oTbl.attr('data-item-original-width'));      
        oTbl.find('tbody tr:eq(0) td').each(function(){
            $(this).width($(this).attr("data-item-original-width"));
        });                 
    }

    $(document).ready(function(){
        scrolify($('#tblNeedsScrolling'), 500); // 500 is height
    });
 </script>

  </head>

  <body>
<?php 
 
// Aktionen 
$aktion = ''; 
if (isset($_GET['aktion'])) {
    $aktion = $_GET['aktion'];
} 
 
if ($aktion == "") { 
    echo 'Admin Area'; 
} 
 
if ($aktion == "print") { 
   ?>
   
   				<div class="container">
				<div class="span 6">
					<div class="row">
						<div class="col-col md-4">
							<h3>Gráficas Redox (mV) / EC (µs) / pH / TDS (ppm) del cliente</h3><h2><?php echo $_SESSION['username']?></h2>
						</div>
					</div>
				</div>
				<div class="span 6">
					<div class="row">
						<div class="col-col md-4">
							<img alt="person_bordered" width="120px" height="133px" src="../images/graph.png" style="width:100px; display: block;">
						</div>
					</div>
				</div>
			</div>
   
    <div class="container">	


		<div class="ToolText" onMouseOver="javascript:this.className='ToolTextHover'" onMouseOut="javascript:this.className='ToolText'"><i class='fa fa-exclamation' style='color:red;'></i><span><?php echo GRAFICAS_HELP; ?></span>
		</div>
		<table id="tblNeedsScrolling" class="sortable" style="width: 1000px;">
              <thead>
                <tr>

				  <th>Cliente</th>
				  
				   <th colspan="4">POZO</th>
				   <th colspan="4">ALMACÉN</th>
				   <th colspan="4">BEBEDERO</th>
				   <th colspan="4">LABORATORIO</th>
                </tr>
				<tr>

						<td>   </td>
				   <th>Redox (mV)</th>
				   <th>EC (µs)</th>
				   <th>pH</th>
				   <th>TDS (ppm)</th>
				   
				   <th>Redox (mV)</th>
				   <th>EC (µs)</th>
				   <th>pH</th>
				   <th>TDS (ppm)</th>
				   
				   <th>Redox (mV)</th>
				   <th>EC (µs)</th>
				   <th>pH</th>
				   <th>TDS (ppm)</th>
				   
				   
				   <th>Redox (mV)</th>
				   <th>EC (µs)</th>
				   <th>pH</th>
				   <th>TDS (ppm)</th>
                </tr>
              </thead>
              <tbody>


            
            <?php
			//error_reporting(E_ALL ^ E_NOTICE);
				

			// We Will prepare SQL Query
				$STM = $dbh->prepare("SELECT  * FROM analiticas WHERE integradora='$_SESSION[username]'");
			// For Executing prepared statement we will use below function
				$STM->execute();
			// we will fetch records like this and use foreach loop to show multiple Results
				$STMrecords = $STM->fetchAll();
			foreach($STMrecords as $row)
				{
			
			 echo"<tr>";
			 
			//echo"<td><img src='assets/img/$row[0].png'>".$row[1]."</td>";
					
			
					echo '<td><a href="#" alt="Image Tooltip" rel="tooltip" content="<table class=print2>
								<tbody>
								<tr>
								
								<th style=width:20%>Cliente</th>
								<th style=width:30%>Fecha/hora</th>
								<th style=width:35% colspan=3>Elem. inspeccionado</th>
								</tr>
								<tr>
								<td>' . $row['id'] . '</td>
								<td>' . $row['username'] . '</td>
								<td>' . $row['fechainicioensayo'] . '</td>
								<td colspan=3>' . $row['origenmuestra'] . '</td>
								</tr>
								<tr style=background-color:rgba(192,192,192,0.3);>
								<th style=color:MidnightBlue; colspan=6><div class=text-center>POZO</div></th>
								</tr>
								<tr>
								<th>Biocida</th>
								<th>Redox</th>
								<th>pH</th>
								<th>Tª</th>
								<th>TDS</th>
								<th>Otros</th>
								</tr>
								<tr>
								<td>' . $row['pbiocida'] . '</td>
								<td>' . $row['predox'] . '</td>
								<td>' . $row['pph'] . '</td>
								<td>' . $row['tempozo'] . '</td>
								<td>' . $row['ptds'] . '</td>
								<td>' . $row['potros'] . '</td>
								</tr>
								<tr style=background-color:rgba(192,192,192,0.3);>
								<th style=color:MidnightBlue; colspan=6><div class=text-center>ALMACENAMIENTO</div></th>
								</tr>
								<tr>
								<th>Biocida</th>
								<th>Redox</th>
								<th>pH</th>
								<th>Tª</th>
								<th>TDS</th>
								<th>Otros</th>
								</tr>
								<tr>
								<td>' . $row['lbiocida'] . '</td>
								<td>' . $row['lredox'] . '</td>
								<td>' . $row['lph'] . '</td>
								<td>' . $row['tempalmacenam'] . '</td>
								<td>' . $row['ltds'] . '</td>
								<td>' . $row['lotros'] . '</td>
								</tr>
								<tr style=background-color:rgba(192,192,192,0.3);>
								<th style=color:MidnightBlue; colspan=6><div class=text-center>BEBEDERO</div></th>
								</tr>
								<tr>
								<th>Biocida</th>
								<th>Redox</th>
								<th>pH</th>
								<th>Tª</th>
								<th>TDS</th>
								<th>Otros</th>
								</tr>
								<tr>
								<td>' . $row['bbiocida'] . '</td>
								<td>' . $row['bredox'] . '</td>
								<td>' . $row['bph'] . '</td>
								<td>' . $row['tempbebedero'] . '</td>
								<td>' . $row['btds'] . '</td>
								<td>' . $row['botros'] . '</td>
								</tr>
								<tr style=background-color:rgba(192,192,192,0.3);>
								<th style=color:MidnightBlue; colspan=6><div class=text-center>OTROS</div></th>
								</tr>
								<tr>
								<th>Biocida</th>
								<th>Redox</th>
								<th>pH</th>
								<th>Tª</th>
								<th>TDS</th>
								<th>Otros</th>
								</tr>
								<tr>
								<td>' . $row['obiocida'] . '</td>
								<td>' . $row['oredox'] . '</td>
								<td>' . $row['oph'] . '</td>
								<td>' . $row['tempotros'] . '</td>
								<td>' . $row['otds'] . '</td>
								<td>' . $row['ootros'] . '</td>
								</tr>
								</tbody>
								</table>" />
							  
							  <span class="icon icon-user" aria-hidden="true"></span> ' . $row['1'] . '
							  </a></td>';
							  
				//echo"<td>".$row[1]."</td>";

				echo "<td><a href='graficasparaclientes/graficaspredox.php?&amp;aktion=print_id&amp;id=".$row['1']."' alt='Gráfica REDOX-POZO de la Granja: ".$row[1]."' title='Gráfica REDOX-POZO de la Granja ".$row[1]."';><span class='icon icon-signal' aria-hidden='true'></span></a></td>";
				 echo "<td><a href='graficasparaclientes/graficaspec.php?&amp;aktion=print_id&amp;id=".$row['1']."' alt='Gráfica EC-POZO de la Granja: ".$row[1]."' title='Gráfica EC-POZO de la Granja ".$row[1]."';><span class='icon icon-signal' aria-hidden='true'></span></a></td>";
				 echo "<td><a href='graficasparaclientes/graficaspph.php?&amp;aktion=print_id&amp;id=".$row['1']."' alt='Gráfica pH-POZO de la Granja: ".$row[1]."' title='Gráfica pH-POZO de la Granja ".$row[1]."';><span class='icon icon-signal' aria-hidden='true'></span></a></td>";
				 echo "<td><a href='graficasparaclientes/graficasptds.php?&amp;aktion=print_id&amp;id=".$row['1']."' alt='Gráfica TDS-POZO de la Granja: ".$row[1]."' title='Gráfica TDS-POZO de la Granja ".$row[1]."';><span class='icon icon-signal' aria-hidden='true'></span></a></td>";
				 
				 echo "<td><a href='graficasparaclientes/graficaslredox.php?&amp;aktion=print_id&amp;id=".$row['1']."' alt='Gráfica REDOX-ALMACÉN de la Granja: ".$row[1]."' title='Gráfica REDOX-ALMACÉN de la Granja ".$row[1]."';><span class='icon icon-signal' aria-hidden='true'></span></a></td>";
				 echo "<td><a href='graficasparaclientes/graficaslec.php?&amp;aktion=print_id&amp;id=".$row['1']."' alt='Gráfica EC-ALMACÉN de la Granja: ".$row[1]."' title='Gráfica EC-ALMACÉN de la Granja ".$row[1]."';><span class='icon icon-signal' aria-hidden='true'></span></a></td>";
				 echo "<td><a href='graficasparaclientes/graficaslph.php?&amp;aktion=print_id&amp;id=".$row['1']."' alt='Gráfica pH-ALMACÉN de la Granja: ".$row[1]."' title='Gráfica pH-ALMACÉN de la Granja ".$row[1]."';><span class='icon icon-signal' aria-hidden='true'></span></a></td>";
				 echo "<td><a href='graficasparaclientes/graficasltds.php?&amp;aktion=print_id&amp;id=".$row['1']."' alt='Gráfica TDS-ALMACÉN de la Granja: ".$row[1]."' title='Gráfica TDS-ALMACÉN de la Granja ".$row[1]."';><span class='icon icon-signal' aria-hidden='true'></span></a></td>";
				 
				 echo "<td><a href='graficasparaclientes/graficasbredox.php?&amp;aktion=print_id&amp;id=".$row['1']."' alt='Gráfica REDOX-BEBEDERO de la Granja: ".$row[1]."' title='Gráfica REDOX-BEBEDERO de la Granja ".$row[1]."';><span class='icon icon-signal' aria-hidden='true'></span></a></td>";
				 echo "<td><a href='graficasparaclientes/graficasbec.php?&amp;aktion=print_id&amp;id=".$row['1']."' alt='Gráfica EC-BEBEDERO de la Granja: ".$row[1]."' title='Gráfica EC-BEBEDERO de la Granja ".$row[1]."';><span class='icon icon-signal' aria-hidden='true'></span></a></td>";
				 echo "<td><a href='graficasparaclientes/graficasbph.php?&amp;aktion=print_id&amp;id=".$row['1']."' alt='Gráfica pH-BEBEDERO de la Granja: ".$row[1]."' title='Gráfica pH-BEBEDERO de la Granja ".$row[1]."';><span class='icon icon-signal' aria-hidden='true'></span></a></td>";
				 echo "<td><a href='graficasparaclientes/graficasbtds.php?&amp;aktion=print_id&amp;id=".$row['1']."' alt='Gráfica TDS-BEBEDERO de la Granja: ".$row[1]."' title='Gráfica TDS-BEBEDERO de la Granja ".$row[1]."';><span class='icon icon-signal' aria-hidden='true'></span></a></td>";
				 
				 echo "<td><a href='graficasparaclientes/graficasoredox.php?&amp;aktion=print_id&amp;id=".$row['1']."' alt='Gráfica REDOX-LABORATORIO de la Granja: ".$row[1]."' title='Gráfica REDOX-LABORATORIO de la Granja ".$row[1]."';><span class='icon icon-signal' aria-hidden='true'></span></a></td>";
				 echo "<td><a href='graficasparaclientes/graficasoec.php?&amp;aktion=print_id&amp;id=".$row['1']."' alt='Gráfica EC-LABORATORIO de la Granja: ".$row[1]."' title='Gráfica EC-LABORATORIO de la Granja ".$row[1]."';><span class='icon icon-signal' aria-hidden='true'></span></a></td>";
				 echo "<td><a href='graficasparaclientes/graficasoph.php?&amp;aktion=print_id&amp;id=".$row['1']."' alt='Gráfica pH-LABORATORIO de la Granja: ".$row[1]."' title='Gráfica pH-LABORATORIO de la Granja ".$row[1]."';><span class='icon icon-signal' aria-hidden='true'></span></a></td>";
				 echo "<td><a href='graficasparaclientes/graficasotds.php?&amp;aktion=print_id&amp;id=".$row['1']."' alt='Gráfica TDS-LABORATORIO de la Granja: ".$row[1]."' title='Gráfica TDS-LABORATORIO de la Granja ".$row[1]."';><span class='icon icon-signal' aria-hidden='true'></span></a></td>";
				echo"</tr>";
			}
			?>

              </tbody>
        </table>

	<?php
} 
if ($aktion == "print_id") { 
   @$id = $_GET['id']; 
$result = mysqli_query($mysqli,  "SELECT username, fechainicioensayo, pbiocida
									FROM  `analiticas` 
									WHERE username LIKE '$_GET[id]'
									AND fechainicioensayo BETWEEN DATE_SUB( NOW( ) , INTERVAL 540 DAY )
									AND NOW( )" );


if ($result) {

	$labels = array ();
	$labels2 = array ();
	$data = array ();

	while ( $row = mysqli_fetch_assoc( $result ) ) {
		$labels [] = $row ["fechainicioensayo"];
		$labels2 [] = $row ["pbiocida"];
		$data [] = $row ["pbiocida"];
	}

	// Now you can aggregate all the data into one string
	$data_string = "[" . join ( ", ", $data ) . "]";
	$labels_string = "['" . join ( "', '", $labels ) . "']";
	$labels2_string = "['" . join ( "', '", $labels2 ) . "']";
	
} else {
	print ('MySQL query failed with error: ' . ((is_object($mysqli)) ? mysqli_error($mysqli) : (($___mysqli_res = mysqli_connect_error()) ? $___mysqli_res : false))) ;
} 
?>
<br /><br />
</div>
 <div class="container">
 
 <?php
		echo "<div class='text-left'>";
		echo "Gráfica de la granja: <span class='text-success'>&nbsp;$id&nbsp;</span>";
		echo "</div>";
		?>
    <canvas id="cvs" width="1100" height="300">[No canvas support]</canvas>
    <script>
        chart = new RGraph.Line('cvs', <?php print($data_string) ?>);
        chart.Set('chart.title', 'Biocida pozo');
        chart.Set('chart.title.yaxis', 'Valor');
        chart.Set('chart.annotatable', true);
        chart.Set('chart.events.click', myFunc);
        chart.Set('chart.events.mousemove', function (e, shape) {e.target.style.cursor = 'pointer';});
        chart.Set('chart.contextmenu', [
                                 ['Show palette', RGraph.Showpalette],
                                 ['Clear', function ()
                                           {
                                            RGraph.Clear(chart.canvas);
                                            RGraph.ClearAnnotations(chart.canvas);
                                            chart.Draw();
                                           }
                                 ]
                                ]);
        chart.Set('chart.background.grid.autofit', true);

        /*chart.Set('chart.background.barcolor1', '#f2f2f2');
        chart.Set('chart.background.barcolor2', '#f2f2f2');
        chart.Set('chart.background.grid.color', 'rgba(238,238,238,1)');*/
		chart.Set('chart.background.grid.autofit.numhlines', 10);
        chart.Set('chart.colors', ['yellow']);
		chart.Set('chart.shadow', true);
        chart.Set('chart.linewidth', 3);
        chart.Set('chart.curvy', 1);
        chart.Set('chart.curvy.factor', 0.25);
        chart.Set('chart.filled', false);
        chart.Set('chart.gutter.left', 75);
        chart.Set('chart.gutter.right', 5);
        chart.Set('chart.gutter.top', 50);
        chart.Set('chart.gutter.bottom', 100);
		chart.Set('chart.text.angle', 45);
        chart.Set('chart.hmargin', 10);
        chart.Set('chart.tickmarks', 'endcircle');
        chart.Set('chart.tooltips', <?php print($labels2_string) ?>);
        chart.Set('chart.labels', <?php print($labels_string) ?>);
        chart.Set('chart.tooltips.effect', 'contract');
           chart.Draw();

            /**
        * This is the function that is called when the Pie chart is clicked on
        */
        function myFunc (e, shape)
        {
            // If you have multiple charts on your canvas the .__object__ is a reference to
            // the last one that you created
            var obj   = e.target.__object__;

            var dataset = shape['dataset'];
            var index   = shape['index_adjusted'];
            var value = typeof(index) == 'number' ? obj.data[dataset][index] : obj.data[dataset];

            alert('Value: ' + value);
        }

    </script>
	<?php
	} 
	?>
	
	</div>
	 <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

	<script type="text/javascript"
			 src="http://cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.min.js">
	</script> 
	<script type="text/javascript" src="../assets/js/sorttable.js"></script>
	<script type="text/javascript" src="../assets/js/thickbox.js"></script>
	<script type="text/javascript" src="../assets/js/queriesttip.js"></script>
</body> 
</html>