<?php
include('acciones.php');
?> 
<a href="?seccion=documentos_admin"><div onMouseOver="showdiv(event,'<?php echo MENU_ALT_ADMINISTRAR_DOCUMENTOS; ?>');" onMouseOut="hiddenDiv()" style='display:table;margin-top3px;'><img src="images/deep#8BC34A_edit.gif" style="position:absolute; left:0px; top:0px;" alt="" /></div></a>&nbsp;                                          
<a href="?seccion=directoryhowto1"><div onMouseOver="showdiv(event,'<?php echo MENU_ALT_MAPA_DOCUMENTOS; ?>');" onMouseOut="hiddenDiv()" style='display:table;margin-top3px;'><img src="images/map.gif" style="position:absolute; left:30px; top:0px;" alt="" /></div></a>&nbsp;
<a href="?seccion=listadocumentos"><div onMouseOver="showdiv(event,'<?php echo MENU_ALT_LISTA_DOCUMENTOS; ?>');" onMouseOut="hiddenDiv()" style='display:table;margin-top3px;'><img src="images/deep#8BC34A_list.gif" style="position:absolute; left:60px; top:0px;" alt="" /></div></a>&nbsp;
<a href="?seccion=directoryhowto_3"><div onMouseOver="showdiv(event,'<?php echo MENU_ALT_ANOTAR_DOCUMENTOS; ?>');" onMouseOut="hiddenDiv()" style='display:table;margin-top3px;'><img src="images/deep#8BC34A_add.gif" style="position:absolute; left:90px; top:0px;" alt="" /></div></a>&nbsp;
<a href="?seccion=directoryhowto_4"><div onMouseOver="showdiv(event,'<?php echo MENU_ALT_APROBAR_DOCUMENTOS; ?>');" onMouseOut="hiddenDiv()" style='display:table;margin-top3px;'><img src="images/deep#8BC34A_ok.gif" style="position:absolute; left:120px; top:0px;" alt="" /></div></a>&nbsp;
<a href="?seccion=wpload"><div onMouseOver="showdiv(event,'<?php echo MENU_ALT_SUBIR_DOCUMENTOS; ?>');" onMouseOut="hiddenDiv()" style='display:table;margin-top3px;'><img src="images/deep#8BC34A_upload.gif" style="position:absolute; left:150px; top:0px;" alt="" /></div></a>&nbsp;
<a href="?seccion=buscaenlaces"><div onMouseOver="showdiv(event,'<?php echo MENU_ALT_BUSCAR_DOCUMENTOS; ?>');" onMouseOut="hiddenDiv()" style='display:table;margin-top3px;'><img src="images/deep#8BC34A_search.gif" style="position:absolute; left:180px; top:0px;" alt="" /></div></a>&nbsp;
<a href="?seccion=checkbox3_links"><div onMouseOver="showdiv(event,'<?php echo MENU_ALT_BORRAR_DOCUMENTOS; ?>');" onMouseOut="hiddenDiv()" style='display:table;margin-top3px;'><img src="images/deep#8BC34A_delete.gif" style="position:absolute; left:210px; top:0px;" alt="" /></div></a>&nbsp;
<a href="?seccion=editdeletedocs"><div onMouseOver="showdiv(event,'<?php echo EDITAR_BORRAR_DOCUMENTO; ?>');" onMouseOut="hiddenDiv()" style='display:table;margin-top3px;'><img src="images/deep#8BC34A_rayo.gif" style="position:absolute; left:240px; top:0px;" alt="" /></div></a>&nbsp;
<a href="?seccion=directoryhowto_5"><div onMouseOver="showdiv(event,'<?php echo MENU_ALT_MODIFICAR_CATEGORIAS; ?>');" onMouseOut="hiddenDiv()" style='display:table;margin-top3px;'><img src="images/deep#8BC34A_categories.gif" style="position:absolute; left:270px; top:0px;" alt="" /></div></a>&nbsp;